---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: minio

resources:
  - namespace.yaml
  - minio-deployment.yaml
  - mc-deployment.yaml
  - minio-service.yaml
  - minio-secret.yaml
  - minio-cm.yaml