apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
  labels:
    app: minio
spec:
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
        - name: main
          image: minio/minio
          env:
            - name: MINIO_ROOT_USER
              valueFrom:
                secretKeyRef:
                  name: minio-cred
                  key: minio_access_key
            - name: MINIO_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: minio-cred
                  key: minio_secret_key
            - name: MINIO_SERVER_URL
              valueFrom: 
                configMapKeyRef:
                  name: minio-config
                  key: minio-server-url
            - name: MINIO_BROWSER_REDIRECT_URL
              valueFrom: 
                configMapKeyRef:
                  name: minio-config
                  key: minio-browser-url
          ports:
            - containerPort: 9000
          command: [minio, server, --console-address, ":9001", /data]
          lifecycle:
            postStart:
              exec:
                command: 
                  - "sh"
                  - "-c"
                  - >
                    mkdir -p /data/my-bucket-1;
                    mkdir -p /data/my-bucket-2
          readinessProbe:
            httpGet:
              path: /minio/health/ready
              port: 9000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /minio/health/live
              port: 9000
            initialDelaySeconds: 5
            periodSeconds: 10